
[namespace.Default]
    BaseType = "/DataTypes/BaseTypes"
    ImplementationDataType = "DataTypes/ImplementationDataTypes"
    CompuMethod = "DataTypes/CompuMethods"
    DataConstraint = "DataTypes/DataConstrs"
    ComponentType = "/ComponentTypes"
    ModeDeclaration = "/ModeDclrGroups"
    PortInterface = "/PortInterfaces"
    Constant = "/Constants"
    base_ref = "/"

[namespace.AUTOSAR_Platform]
    BaseType = "BaseTypes"
    CompuMethod = "CompuMethods"
    DataConstraint = "DataConstrs"
    ImplementationDataType = "ImplementationDataTypes"

[document.AUTOSAR_Platform]
    packages = "/AUTOSAR_Platform"

[document.PortInterfaces]
   packages=["/ModeDclrGroups", "/PortInterfaces"]

[document.DataTypes]
    packages = "/DataTypes"

[document.Constants]
    packages = "/Constants"

[document_mapping.ComponentType]
    package_ref = "/ComponentTypes"
    element_types = "SwComponentType"
    suffix_filters = ["_Implementation"]

[behavior]
    background_event_prefix = "BT"
    data_receive_error_event_prefix = "DRET"
    data_receive_event_prefix = "DRT"
    init_event_prefix = "IT"
    operation_invoked_event_prefix = "OIT"
    swc_mode_manager_error_event_prefix = "MMET"
    swc_mode_switch_event_prefix = "MST"
    timing_event_prefix = "TMT"
    data_send_point_prefix = "SEND"
    data_receive_point_prefix = "REC"
    server_call_point_prefix = "SC"
