python examples/xml/data_types/application_data_type.py
python examples/xml/data_types/compu_method_rational.py
python examples/xml/data_types/compu_method_value_table.py
python examples/xml/data_types/implementation_data_type.py
python examples/xml/data_types/sw_addr_method.py
python examples/xml/data_types/sw_base_type.py
python examples/xml/constant/create_constants.py
python examples/xml/unit/unit.py
python examples/xml/port_interface/nv_data_interface.py
python examples/xml/port_interface/parameter_interface.py
python examples/xml/port_interface/sender_receiver_interface.py
python examples/xml/port_interface/client_server_interface.py
python examples/xml/port_interface/mode_switch_interface.py
python examples/xml/component/application_component.py
python examples/xml/component/composition_component.py
python examples/xml/reader/print_errors.py
python examples/xml/reference/reference_example.py
python examples/xml/port/explicit_send_receive.py
python examples/xml/port/implicit_read_write.py
python examples/xml/port/mode_switch.py
python examples/xml/port/port_api_options.py
python examples/xml/common_structure/write_admin_data.py
python examples/xml/common_structure/read_admin_data.py
python examples/template/generate_xml_using_config.py
python examples/template/generate_xml_without_config.py
python examples/generator/data_types/gen_type_defs_scalar.py
python examples/generator/data_types/gen_type_defs_array.py
python examples/generator/data_types/gen_type_defs_record.py